"""create statistics table

Revision ID: ce8dc013c2e2
Revises:
Create Date: 2022-07-19 22:01:49.781984

"""
from alembic import op
import sqlalchemy as sa

from app.models import Statistic


# revision identifiers, used by Alembic.
revision = 'ce8dc013c2e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('current_winning_streak', sa.Integer(), nullable=False),
    sa.Column('longest_winning_streak', sa.Integer(), nullable=False),
    sa.Column('longest_losing_streak', sa.Integer(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    seed()

def seed():
    op.bulk_insert(Statistic.__table__,
        [
            {'won': 0, 'lost': 0, 'current_winning_streak': 0, 'longest_winning_streak': 0, 'longest_losing_streak': 0, 'total_games': 0},
            {'won': 0, 'lost': 0, 'current_winning_streak': 0, 'longest_winning_streak': 0, 'longest_losing_streak': 0, 'total_games': 0}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
